### PR TITLE
Dynamically generate chart, based on categories

### PR DESCRIPTION
**Pull request by Seanstoppable**
Made an attempt to categorize based on what existed, and reading
descriptions.
Numbers seem to be discrepant in a few places
Will mean that people just need to make post and categorize
appropriately

### CODE REVIEW

**Comment by magoo** [comment]
Interesting, I'll have to look at this a bit later. I was not very disciplined with matching post categories to root causes, but I could be in the future. I am curious if the result would be the same or similar. This would also allow me to have better tracking of multiple categories per post.

**Comment by Seanstoppable** [comment]
No problem! Just noticed that these were being updated manually, and thought there should be a better way to do it, making it easier for people to contribute posts without having to update all the other bits.

**Comment by Seanstoppable** [comment]
I've taken another stab at this, that also dynamically generates the columns (there are 12 distinct categories today, after an attempt to normalize a bit). Outstanding work is generating a range of colors, vs the drab grey that is there now.

**Comment by Seanstoppable** [comment]
After some cleanup, it currently looks like the following, where the colors are somewhat random at generation time:
screen shot 2019-02-15 at 5 13 49 pm

**Comment by magoo** [comment]
This looks great. The blocking issue is that I manually sorted these into buckets early on, so that categorization is lost. For this to relate to my opinions on how these are sorted, I'll have to go through all of them again and make sure they're tagged correctly. The graph may change a bit as a result, which I think is OK, but I'll have to go through every post and make sure they're tagged correctly. 

This being more than a couple hours of my time, I don't know when I can get to this.

**Comment by magoo** [comment]
I've updated categories so this better reflects my previous opinions (with some new categories!) If you can fix the color part so they're consistently pretty, lmk and I'll merge. Otherwise I'll take a peek and see if I can update it myself. They can be pretty gross if more categories are added.

**Comment by Seanstoppable** [comment]
The more I play around with dynamic colors, the more awful things become. 

2 options I can think of:

1) Hand select enough colors (a dozen or so), so you don't immediately have to update those as you expand.
2) Pick a good base set of colors, and then rotate through those. I.e, take your original colors, and once we hit the last one, the next column takes on the same color as the first column.

**Comment by magoo** [comment]
I like option 2. I don't think it will stand out that colors repeat, so long as they're distanced.

**Comment by Seanstoppable** [comment]
Done! Here is an updated screenshot
image

**Pull request merged**
